-- Market system: allows players to post offers and requests for items.

CREATE TYPE public.market_listing_type AS ENUM ('offer', 'request');
CREATE TYPE public.market_listing_status AS ENUM ('active', 'fulfilled', 'cancelled');

CREATE TABLE public.market_listing (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ap_tracker_id INTEGER NOT NULL REFERENCES ap_tracker (id) ON DELETE CASCADE ON UPDATE CASCADE,
    ct_user_id INTEGER NOT NULL REFERENCES ct_user (id) ON DELETE CASCADE ON UPDATE CASCADE,
    ap_game_id INTEGER NOT NULL REFERENCES ap_game_store (id) ON DELETE CASCADE ON UPDATE CASCADE,
    game_name TEXT NOT NULL,
    item_name TEXT NOT NULL,
    listing_type market_listing_type NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    status market_listing_status NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX market_listing_tracker_game_idx ON market_listing (ap_tracker_id, game_name);
CREATE INDEX market_listing_user_idx ON market_listing (ct_user_id);
CREATE INDEX market_listing_matching_idx ON market_listing (ap_tracker_id, game_name, item_name, listing_type, status);

CREATE CAST (text AS market_listing_type) WITH INOUT AS ASSIGNMENT;
CREATE CAST (text AS market_listing_status) WITH INOUT AS ASSIGNMENT;
